---

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  sudo: no

- name: Copy WordPress wp-config file
  template: src=wp-config.php dest={{site.www_root}}

- name: Copy WordPress index
  template: src=index.php dest={{site.www_root}}

- name: Delete default html directory
  file: path={{site.www_root}}/html state=absent

- name: Download WordPress
  get_url: url=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/var/www/wordpress-{{ wp_version }}.tar.gz

- name: Extract archive
  unarchive: src=/var/www/wordpress-{{wp_version}}.tar.gz
             dest="{{site.www_root}}/"
             copy=no

- name: Rename the wordpress folder to wp
  command: mv {{site.www_root}}/wordpress {{site.www_root}}/wp

- name: Delete WordPress Tarball
  file: path=/var/www/wordpress-{{ wp_version }}.tar.gz state=absent