---
- name: Install MySQL Server
  apt: name=mysql-server state=present

- name: Install MySQL Client
  apt: name=mysql-client state=present

- name: Install MySQL Python for MySQL User/DB automation
  apt: name=python-mysqldb state=present

- name: Delete anonymous MySQL server user for current hostname
  action: mysql_user user='' host={{ ansible_hostname }} state=absent

- name: Delete anonymous MySQL server user for localhost
  action: mysql_user user='' state=absent

- name: Remove the test database
  mysql_db: name=test state=absent

- name: Add WordPress Database
  mysql_db: name={{database.name}} state=present

- name: Add Database user with privileges
  mysql_user: name={{database.user}}
              password={{database.password}}
              priv={{database.name}}.*:ALL
              state=present