---
- name: Update Apt
  apt: update_cache=yes

- name: Checking essentials
  apt: name={{ item }} state=present
  with_items:
  - python-software-properties
  - python-pycurl
  - build-essential
  - python-mysqldb
  - curl
  - git
  - tree
  - man

- name: Copy aliases
  copy: src=../files/aliases dest=/home/vagrant/.aliases owner=vagrant mode=0600

- name: Copy bash_profile
  copy: src=../files/bash_profile dest=/home/vagrant/.bash_profile owner=vagrant mode=0600